name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with Gradle
        run: ./gradlew publish
        env: # Or as an environment variable
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Set up Nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Generating API docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Build Demos
        run: ./gradlew headless-demo:build examples-demo:build metadataToWww

      - name: Build Webpage
        working-directory: ./www
        run: npm install && npm run build

      - name: Copy api docs to webpage
        run: mkdir -p ./www/_site/api && cp -r ./api/* ./www/_site/api

      - name: Copy headless-demo files to webpage
        run: mkdir -p ./www/_site/headless-demo && cp ./headless-demo/build/distributions/* ./www/_site/headless-demo

      - name: Copy examples-demo files to webpage
        run: mkdir -p ./www/_site/examples-demo && cp ./examples-demo/build/distributions/* ./www/_site/examples-demo

      - name: Releasing www page
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: jwstegemann/fritz2-web
          target_branch: master
          keep_history: false
          jekyll: false
          fqdn: www.fritz2.dev
          build_dir: ./www/_site
        env:
          GH_PAT: ${{ secrets.FRITZ2_WEB_TOKEN }}
